### ISSUE TITLE
Crash on selector

### ISSUE THREAD

**Issue by squi2rel** [I-hope1/mod-tools#10]
When I use selector selected a lot of solar panel and kill them, game crashed.

[E] java.lang.NullPointerException: Cannot read field "team" because the return value of "arc.struct.Seq.first()" is null
        at mindustry.world.blocks.power.PowerGraph.update(PowerGraph.java:224)
        at mindustry.gen.PowerGraphUpdater.update(PowerGraphUpdater.java:195)
        at mindustry.entities.EntityGroup.update(EntityGroup.java:85)
        at mindustry.gen.Groups.update(Groups.java:83)
        at mindustry.core.Logic.update(Logic.java:486)
        at arc.ApplicationCore.update(ApplicationCore.java:37)
        at mindustry.ClientLauncher.update(ClientLauncher.java:275)
        at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
        at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:41)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at mindustry.desktop.DesktopLauncher0.main(DesktopLauncher0.java:10)

**Comment by I-hope1** [comment]
这个替换/删除是异步的，遇到这个同步的电力更新，确实会崩溃

**Comment by I-hope1** [comment]
你要不要测试一下最新版本(1.4.6.2)
