### ISSUE TITLE
info crash

### ISSUE THREAD

**Issue by squi2rel** [I-hope1/mod-tools#11]
new Date() info

[E] java.lang.NumberFormatException: For input string: "40.0"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:661)
	at java.base/java.lang.Integer.parseInt(Integer.java:777)
	at modtools.utils.MySettings$Data.getInt(MySettings.java:155)
	at modtools.events.ISettings.getInt(ISettings.java:103)
	at modtools.ui.content.debug.Tester.compileAndExec(Tester.java:529)
	at modtools.ui.content.debug.Tester.lambda$build$8(Tester.java:206)
	at arc.scene.Element$9.changed(Element.java:988)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:370)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:136)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:181)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:190)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:41)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at mindustry.desktop.DesktopLauncher0.main(DesktopLauncher0.java:10)

**Comment by I-hope1** [comment]
How did it happen?

**Comment by squi2rel** [comment]
just that
![image](https://github.com/user-attachments/assets/069f89c1-3314-4bc9-bb8d-95cdeae7a118)
randomly happen

**Comment by I-hope1** [comment]
The return value of slider is float, but if I want to get int, the parsing error occurs.
So now I added a program to convert float to int.
