### ISSUE TITLE
Crash when bind key to a server button

### ISSUE THREAD

**Issue by squi2rel** [I-hope1/mod-tools#17]
![image](https://github.com/user-attachments/assets/00b0aee6-bb4d-4486-bdbe-e2080a803698)

java.lang.NullPointerException: Cannot invoke "arc.scene.ui.TextField.setText(String)" because "this.field" is null
        at modtools.content.KeyCodeSetter$KeyCodeBindWindow.show(KeyCodeSetter.java:189)
        at modtools.content.KeyCodeSetter.lambda$selectButton$17(KeyCodeSetter.java:343)
        at modtools.ui.TopGroup$1.touchUp(TopGroup.java:495)
        at arc.scene.event.InputListener.handle(InputListener.java:31)
        at arc.scene.Scene.touchUp(Scene.java:370)

**Comment by I-hope1** [comment]
Ok, thanks for your feedback.
