### ISSUE TITLE
Crash on watching elements

### ISSUE THREAD

**Issue by squi2rel** [I-hope1/mod-tools#9]
[E] java.lang.IndexOutOfBoundsException: index can't be >= size: 4 >= 4
	at arc.struct.Seq.get(Seq.java:465)
	at modtools.ui.content.ui.ReviewElement$MyWrapTable.lambda$new$10(ReviewElement.java:496)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at mindustry.desktop.DesktopLauncher0.main(DesktopLauncher0.java:10)

![output](https://github.com/I-hope1/mod-tools/assets/102400902/706a0088-9d47-45f2-892a-9e6e9ddf583a)

**Comment by I-hope1** [comment]
It may be solved on the lastest version.
